### ISSUE TITLE
To-do List in renew branch

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#113]
## 高优先级
1. [x] 修复Vec问题 (179d5b8caf5b6a57922d54b9a69463ba97054437)
2. [ ] 修改架构
   - [x] 线程池更新
   - [x] 网络 (RakNet->rpclib) (d5e4f6e1e4f26650c320985c682e1950f63999a6)
   - [ ] 渲染 (OpenGL-> bgfx) / GLES
   - [x] UI (Dear Imgui->nuklear) (61ab0cb9c23bd456dca7c4445e6e0e4244928c80)
3. [x] 多人 (d5e4f6e1e4f26650c320985c682e1950f63999a6)

## 中优先级
1. [ ] 退游戏崩溃

## 游戏性
1. [x] 鼠标控制视角 (1b5a2106e1f6111818b628d595eaf69e6e844dbc)
2. [x] 重力 (ed5e5a2c4b7f8a330065dd96674aad24b5a1de2d)
3. [ ] 液态水
4. [ ] 开始菜单
5. [ ] 光影水反
6. [ ] VR 支持
7. [ ] 背包
8. [x] 拾取

## 优化
1. [ ] VertexArray 优化(动态增长的VertexArray)
2. [ ] 空区块优化(空区块不储存chunk数据)
3. [ ] Frustum 优化(玩家看不到的区域不渲染)
4. [ ] HeightMap 优化(缓存生成的地形)
5. [ ] 内存池
6. [ ] 多线程渲染检测
7. [ ] 无锁队列
8. [ ] 单人模式不使用网络（优化RPC）

**Comment by DWVoid** [comment]
修复vec问题是啥？

**Comment by harrynull** [comment]
修复Vec问题: 179d5b8caf5b6a57922d54b9a69463ba97054437

**Comment by DWVoid** [comment]
Shall we use another library instead of bgfx? Testing shows that it is not that stable as we think it is @harrynull

**Comment by harrynull** [comment]
@DREAMWORLDVOID What's your suggestion?

**Comment by AnkingLin** [comment]
开始菜单用imgui做不好看吧。。。

**Comment by harrynull** [comment]
@Cawell-Anki 是nuklear
