### ISSUE TITLE
To-do List & Road map 未完成的功能/特性

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#46]
主要列出了NEWorld计划中的功能与特性，由全体开发者维护，所有人都可以回复提出新的功能/建议
_按照“排序靠后的可能依赖于排序靠前的”的顺序排序，原则上各开发者可以选择喜欢的做_
# 近期
- [x] Chunk与不透明方块渲染
- [x] Appveyor/TravisCI编译
- [x] x64支持
- [x] 世界渲染
- [x] 玩家移动和碰撞
- [ ] 可扩展UI系统完善
- [ ] UDP多人游戏
- [x] 网络与数据包格式定义与解析
- [ ] 完善UI（设置界面、多人游戏）
- [ ] 聊天功能与命令系统
- [ ] 实体(entity)与生物
- [ ] 自定义模型方块(透明方块)
- [ ] 液体
- [ ] 其他玩家可视与动作同步
- [ ] 基础的物品系统
- [ ] 容器
- [ ] 掉落物
- [ ] 插件接口：物品
- [ ] 插件接口：方块
- [ ] 插件接口：实体
- [ ] 工具、防具、武器物品
- [ ] 时间
- [ ] 天空，云与天气
- [ ] 光照系统
- [ ] 粒子渲染
# 远期
- [ ] 基础方块与实体渲染系统
- [ ] 流畅的多人游戏与互动
- [ ] 基础的自然系统
- [ ] 自由的插件接口
- [ ] 单人模式优化

**Comment by Miigon** [comment]
这些功能都太远了吧
有没有近期一点的

**Comment by abc612008** [comment]
你来制定啊，我想不太出来

**Comment by Miigon** [comment]
milestone是手贱。。。

**Comment by DREAMWORLDVOID** [comment]
说UI的，帮忙想一套控件接口规范

**Comment by DREAMWORLDVOID** [comment]
大部分都可以封装掉，但是当中还有一个大量使用的boost::signal2::signal没法很方便的封装

**Comment by Miigon** [comment]
signal能不能自己实现一套类似的呢?

**Comment by DREAMWORLDVOID** [comment]
@Miigon 自己的效率不够，不建议这样做

**Comment by Miigon** [comment]
@DREAMWORLDVOID 是因为没有模板的原因？

**Comment by DREAMWORLDVOID** [comment]
@Miigon 正相反，就是模版惹出的问题。其它的资源我可以设计一个handle类来解决，但是这个东西封装不了，因为参数和类型都不确定

**Comment by Miigon** [comment]
@DREAMWORLDVOID 我指的是是否因为自己实现的版本没有用到模板才导致效率低下
在NW中使用到signal2的部分可不可以仅仅使用函数指针之类的来实现呢？
实现一个无模板的signal2子集还是可能的

**Comment by DREAMWORLDVOID** [comment]
@Miigon 不可能，因为需要大量采用带有捕获的lambda表达式，是函数对象，传统的函数指针无法实现

**Comment by Miigon** [comment]
那么在NW中使用到signal2的部分必须暴露接口么？

**Comment by ascchrvalstr** [comment]
说一下，不是signal2是signals2

**Comment by Miigon** [comment]
@ascchrvalstr 所以我讨论的是关于PluginAPI的部分，这部分不可能静态链接
我在linux上UILib就是使用静态链接
如果我和 @DREAMWORLDVOID 谈的不是我想象中那部分的话。。那就到此为止吧，UILib的接口没有什么好争论的

**Comment by bridgekat** [comment]
6934313bd4696c94d935d6153657ffc0ea016d40 Chunk与不透明方块渲染

**Comment by harrynull** [comment]
1f498b726d1f975e44c9a946bf8f394b1e95d222 Appveyor/TravisCI编译

**Comment by harrynull** [comment]
cb472f2214b7dc343138405cb4dd421ca5ad3fd3 x64支持

**Comment by bridgekat** [comment]
a58a5a4a419817f34cfd0a3cf48697aff4fa184d 世界渲染

**Comment by harrynull** [comment]
3e5a0dc6b02d04337ae538d4ecff51d6d653420f 网络基础
